---
collections:
  - name: ansible.netcommon
  - name: ansible.posix
  - name: ansible.windows
  - name: ansible.utils
  - name: community.network
  - name: community.windows
  - name: community.vmware
  - name: community.docker
  - name: community.kubernetes
  - name: community.aws
  - name: community.general
  - name: community.crypto
  - name: community.internal_test_tools
  - name: vmware.vmware_rest
  - name: cloud.common
  - name: netbox.netbox

roles:
  - geerlingguy.docker
  - geerlingguy.java
  - geerlingguy.pip
  - geerlingguy.repo-epel
  - geerlingguy.git
  - geerlingguy.awx
  - geerlingguy.nodejs
  - geerlingguy.filebeat
  - geerlingguy.logstash
  - geerlingguy.ansible
  - geerlingguy.certbot
  - geerlingguy.redis
  - geerlingguy.nfs
  - geerlingguy.daemonize
  - jborean93.win_openssh
