---
roles:
  - geerlingguy.docker
  - geerlingguy.java
  - geerlingguy.pip
  - geerlingguy.repo-epel
  - geerlingguy.git
  - geerlingguy.awx
  - geerlingguy.nodejs
  - geerlingguy.filebeat
  - geerlingguy.logstash
  - geerlingguy.ansible
  - geerlingguy.certbot
  - geerlingguy.redis
  - geerlingguy.nfs
  - geerlingguy.daemonize
  - jborean93.win_openssh
  - monolithprojects.github_actions_runner
